sudo: required
services:
  - docker

before_install:
  - docker build -t spmonkey/docker-react -f Dockerfile.dev .

script:
  - docker run spmonkey/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-415883544547"
  bucket_path: "docker-react"
  on:
    branch: master